context/context.go, templater/templater.go
A resource set collection is a resource set with an addition 'include' array
configured. It is a short-hand for importing multiple resource sets from the
same folder and for excluding/including them as a group.
See https://github.com/tazjin/kontemplate/issues/9 for more information.
Closes #9
=> feat context: Add support for resource set collections

templater/templater.go, templater/templater_test.go, templater/testdata/test-template.txt
Golang's template package now has an option for failing if template variables
are missing: https://golang.org/pkg/text/template/#Template.Option
This updates the templater code to make use of that option and return the
errors encountered during templating.
This fixes #1
=> feat templater: Fail if values are missing

main.go
Instead of printing a spooky stacktrace when the user forgets to specify
the `-f` argument, return an error a lot more gracefully.
=> fix main: Don't panic if file is unspecified

templater/templater.go
After filtering resource sets, check whether any resource sets "survived".
Otherwise it can be assumed that the user specified invalid exclude/include
combinations and should be warned about that.
Fixes #35
=> feat templater: Warn if no valid resource sets are included

.gitignore, README.md, build-release.sh, main.go
* Adds a way for kontemplate to print its current version (and git hash)
* Adds a simple release script
=> Add simple release procedure

build-release.sh, main.go
If kubectl fails during a kontemplate run, kontemplate should also
exit with a non-zero status code.
This fixes #43
=> fix main: Exit with kubectl status code

kontemplate.rb
Adds a Homebrew formula that downloads and installs the 1.0.2 binary release.
Users should be able to "tap" this formula from OS X, the README will be updated in a separate commit.
This fixes #41
=> feat build: Add Homebrew binary formula

image/Dockerfile, image/README.md, image/hashes
Adds a simple Docker image that can be used in CI pipelines to deploy
`kontemplate`-based environments.
This image contains kontemplate and all of its dependencies (including
pass as an optional dependency).
=> feat image: Add Dockerfile for CI pipeline image

main.go, templater/templater.go
Please see the individual commits for more information. This resolves #51 and #56, but does not yet implement the missing resource separator warning inside of a single resource set.
=> Pass rendered resource sets to kubectl individually

templater/templater.go
To prevent situations where a shell auto-appends a slash to an
include/exclude specification on the CLI, trailing slashes in those
string lists are now trimmed.
This fixes #54
=> fix templater: Ignore slash-suffixes on includes/excludes

.travis.yml, context/context.go, context/context_test.go, context/testdata/import-vars-override.yaml, context/testdata/import-vars-simple.yaml, context/testdata/test-vars-override.yaml, context/testdata/test-vars.yaml, main.go, util/util.go
Kontemplate context specifications can now load extra variables from YAML or JSON files by specifying a list of files (relative to the context file) under the `import` key.
This is still missing documentation, but I may redo some parts of the documentation anyways as it was pointed out to me that the default-value functionality is non-obvious, too.
cc: @Globegitter
This implements #64
=> Support importing additional variables from files 

context/context.go, context/context_test.go, context/testdata/explicit-path.yaml, context/testdata/explicit-subresource-path.yaml, templater/templater.go
Instead of always inferring the path at which files in a resource set
are located, let users override the path by specifying a `path` field.
This makes it possible to add the same resource set multiple times
with different values while still keeping distinct names for
addressability (for example when using include/exclude).
This fixes #70
=> Allow overriding of resource set paths

kontemplate.frm
Several bugfixes, nothing major. Skipped one "outdated" dependency
because the only change was a new text file.
=> chore build: Bump dependency versions

image/Dockerfile, image/hashes, kontemplate.rb
There is something weird going on with the Dockerfile: In some versions of Docker (`*sigh*`) the `ADD` instruction will now *extract* remote-downloaded archives (it previously (?) only extracted archives if copied from local disk).
This means that the signature verification will break because it expects a file on disk, however it still seems to work "correctly" on Docker Hub's build system so I should get this out asap.
=> Bump Dockerfile and Homebrew versions

context/context.go
In other places in Kontemplate that deal with YAML files, both the
".yaml" and ".yml" extension are supported.
This fixes context loading code to support that for resource set
variables, too.
This fixes #83
=> fix context: Support ".yml" extension on default files

context/context.go, templater/templater.go, util/util.go
After the change from #84 default variable files with the '.yml'
extension got templated as resource set templates accidentally.
This resolves the issue by moving the list reserved default file names
to a common place and reusing it in both the templater and context pkg.
This fixes #85
=> fix templater: Don't template default.yml files

main.go, templater/templater.go
There were some minor, tricky issues with this. Maybe I need some testing around the execution of the whole process, or maybe #72 so I can test this somewhat more easily.
=> Ensure that nonexistent / empty resource sets are handled correctly

build-release.sh, kontemplate.frm, main.go
This release comes with minor usability improvements and features.
* A new 'lookupIPAddr' template function is available for resolving
DNS A records in templates. Thanks to @landro for the pull request!
* Handling of "non-standard" resource set structures has been improved
to result in better error messages and behaviour in several places.
Release binaries are signed with GPG key `66F505681DB8F43B` which is
verified on my Github profile.
--------------
Note: This is the last Kontemplate release that will be written in Go.
Rob Pike's art project has proven its point but I believe it is
ethically questionable and morally indefensible to continue on this
path.
You can track #72 for the Rust-rewrite of Kontemplate.
=> Version 1.3.0

docs/cluster-config.md
Thanks to @christopher376 on the Kubernetes Slack for pointing out this mistake.
=> docs(cluster-config): 'context' key optional for template command

release.nix
Pin the nixpkgs-commit used for building the Kontemplate release to a
specific commit.
Kontemplate builds should now be fully repeatable (and most likely
reproducible!) on any machine running Nix.
=> feat(build): Pin nixpkgs used for release build

context/context.go, deps.nix, example/some-api/some-api.yaml, main.go, templater/dns.go, templater/pass.go, templater/templater.go
Removes the old error handling library and switches to plain
fmt.Errorf calls.
There are several reasons for this:
* There are no useful types or handling here anyways, so output format
is the only priority.
* Users don't care about getting stacktraces.
* My emotional wellbeing.
Fin de siècle.
=> refactor: Remove old error handling library

build-release.sh, example/some-api/some.cfg, main.go
It's time for a release, maybe a bit unexpected due to how things went.
Anyways, in terms of release process this one doesn't need a release-branch anymore - just a git tag will do now, thanks to Nix :-)
=> Bump version to 1.4.0

docs/templates.md, templater/templater.go
A template function has been added that allows one to template the
Git hash of the surrounding repo. This is useful to be able to inspect the
deployment revision of an object in Kubernetes.
This PR is confirmation that I transfer any copyright of this code to the owner of this repo `tazjin`.
=> Feature: Add new template function called gitHEAD

context/context.go, context/context_test.go, context/testdata/import-vars-override.yaml, main.go, templater/templater.go
These changes allows variables to be defined as an argument when executing `kontemplate` via one or more `--variable` arguments.
With this in place one can either define new variables or override existing variables loaded from a file:
```
$ kontemplate apply --variable version=v1 example/fancy-app.yaml
```
This avoids the need to write variables into a temporary file that is only needed to provide "external variables" into resource sets.
I'm personally not opinionated about the argument name, more than open for better suggestions like `--set` or similar. Any thoughts?
Closes #122
=> Allow explicit variables to be defined as argument

context/context.go, context/context_test.go, main.go, util/util.go
Modifies the logic for importing variables to support absolute paths on the filesystem.
In addition to normal files an absolute path can also be a path such as `/dev/stdin`, which gives users the ability to load extra variables from standard input.
In addition YAML/JSON parsing now use the same library (because - as @cellofellow pointed out in #131 - JSON is a subset of YAML).
This closes #131
=> Support importing variables from absolute paths

context/context.go
In some cases the value of a variable may contain an equals sign,
which would not work in the previous version.
This uses `SplitN` to split the variable specifier into a
pre-determined number (2) of sub-slices. Further `=`-symbols will then
be included in the second substring.
=> fix(context): Use SplitN to split CLI variable specifications

main.go
This lets users choose the executable (either by full path or via a
$PATH-entry) to be used when executing `kubectl`.
This is useful in, for example, OpenShift based setups.
This fixes #143
=> feat(main): Add CLI flag for setting kubectl executable

templater/templater.go, templater/templater_test.go, templater/testdata/test-default.txt
Howdy @tazjin!
These changes adds the `definedOrEmpty` template function which allows templates to get values from possibly non-existent variables in a safe manner.
If no variable exists with the name provided, an empty string will be returned. This makes it a good fit for combining with sprig's `default` function:
```
{{ definedOrEmpty "version" | default gitHEAD }}
```
Would either result in the `version` variable's value, or if it has not been declared, would use the result of `gitHEAD` function instead.
Any thoughts?
*P.S. I'm not opinionated about the function name.*
Refs https://github.com/tazjin/kontemplate/issues/140#issuecomment-397911172
=> Add function to safely check variable existence in templates

deps.nix
Updates the following dependencies to latest:
* Masterminds/semver
* Masterminds/sprig
* ghodss/yaml
* satori/go.uuid -> google/uuid
* huandu/xstrings
* imdario/mergo
* crypto
* alecthomas/kingpin.v2
* yaml.v2
As usual Go libraries are YOLO-versioned, so who knows what changed
here. I'll be going through `sprig` at least to add that to the
changelog.
This relates to #152.
=> Bump dependencies before 1.7.0 release

context/context.go, context/context_test.go, context/testdata/flat-with-args-test.yaml, docs/resource-sets.md, main.go, templater/templater.go
Fixes #157 
Adds support for specifying extra kubectl args per ResourceSet. This allows applying parts of the configuration with options such as `--as=admin`.
I settled on the name `args` because that's already in use for building the `kubectl` command in `main.go`.
I added a test that verifies that the options are, in fact, parsed and added to the `ResourceSet` objects.
Even though the `Args` are actually fetched from the `ResourceSet` directly in `main.go`, I added the test to `context_test.go` because it already had a lot of setup for testing the content of `ResourceSet`s.
I'm not sure how to test that the arguments are actually passed in to `kubectl` correctly. If you point me in the right direction, I'll be happy to add a test :smile:
Also please note that this is my first time doing …
=> feat(main): Support specifying kubectl args in ResourceSets

default.nix
Changes in the Go build environment for Nix have caused the parallel
vetting to run in a subshell which does not have the required function
definitions.
This commit fixes the error by not running vet in parallel (there's no
point to that anyways as the project is tiny).
=> fix(build): Make Nix build work with recent nixpkgs

docs/templates.md, docs/tips-and-tricks.md, templater/templater.go, templater/templater_test.go, templater/testdata/test-insertTemplate.txt
Similar to insertFile, but runs the templating against the file before inserting.
This is useful for sharing common config between yaml files, e.g. volume mounts in a deployment.yaml and cronjob.yaml, and it's useful to be able to use the `configHash` annotation pattern with a templated configmap.yaml
=> feat(templater): Add insertTemplate function

context/context.go, context/context_test.go, templater/templater.go
Resolving of files (for `insertFile` and `insertTemplate`) should
always be relative to the resource set location, the previous
behaviour was considered a bug.
This is fixed by ensuring that resource set paths are absolute at
context loading time.
=> Ensure resource set paths are made absolute
