tazjin/kontemplate

context/context.go

feat context: Add YAML loading support

---

README.md
main.go

Add support for kubectl apply

---

README.md
main.go

Add 'delete' command

---

context/context_test.go
context/testdata/collections-test.yaml
context/testdata/flat-test.yaml
templater/templater_test.go

Add tests for context & templater

---

main.go

fix main: Add a forgotten error check

---

context/context.go
context/context_test.go
context/testdata/parent-variable-override.yaml
context/testdata/parent-variables.yaml
templater/templater.go
util/util.go
util/util_test.go

Variable inheritance for sub resource sets

---

context/context.go
context/context_test.go
context/testdata/default-loading.yaml
context/testdata/default/default.yaml
templater/templater.go

See individual commits.
Relates to #28, #25, #30

Support resource set default values

---

README.md
main.go

See commit messages for more information.
Fixes #26

Move to Kingpin CLI library

---

README.md
docs/templates.md
docs/tips-and-tricks.md

This adds documentation for common questions such as "What is the template format like?" and also some tips & tricks.
There is a lot of room for more docs but this should be good enough for a 1.0 release.
Fixes #19

Add some more documentation

---

build-release.sh
kontemplate.frm
main.go

Repeatable builds

---

build-release.sh
image/Dockerfile
image/hashes
kontemplate.frm
kontemplate.rb
main.go

This PR contains the version bump & new hashes for release 1.1.0, it should be merged after the release is created and uploaded on Github.

Release 1.1.0

---

CODE_OF_CONDUCT.md
README.md

As dictated by the goddess to the eternal polyfather of love.
Signed-off-by: Reverend Dr. J. Kubernaughtt The Most Recent <tazjin@gmail.com>

docs: Add official code of conduct

---

README.md
context/context.go
docs/cluster-config.md
docs/resource-sets.md
docs/templates.md
docs/tips-and-tricks.md

Addresses points discussed in #67.

WIP: Revamp documentation

---

build-release.sh

Fix Windows executables and improve release process

---

main.go

If a resource set is specified by the user and does _not_ contain any
templates, a warning will now be printed.
This fixes #79

feat main: Warn if resource set contains no templates

---

templater/dns.go
templater/templater.go

Using this for passing IP addresses to GKE Kubernetes Service (type LoadBalancer)

Add template method to look up IP addresses from local DNS resolver

---

README.md

Never got around to writing them and maybe they shouldn't be hanging around.

docs(README): Remove dead links

---

templater/templater.go

This makes it so that when gitHead is called in a template the git hash that is returned is the hash of the dir containing the template, not the hash of the dir where kontemplate is called.
resolves issue raised [here](https://github.com/tazjin/kontemplate/pull/123#issuecomment-377318961)

fix(templater): add baseDir to gitHead cmd so that directory is overwritten

---

CONTRIBUTING.md

This document is intended to provide some information about how to
contribute to the project, from basic sanity checks and code quality
to information about how to structure git commits.
These are the most common things that I encounter in pull requests
sent to my projects.

docs: Add contribution guidelines

---

build-release.sh
main.go

Bump version to 1.6.0

---

README.md
image/Dockerfile
image/hashes
kontemplate.rb

Bump image & Homebrew formula for 1.7.0
